version: '3.8'

services:
  database:
    image: postgres:16.0-bookworm
    container_name: fullstack-psql
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - fullstack:/var/lib/postgresql/data

volumes:
  fullstack:
