POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Testi",
    "author": "Minä",
    "url": "https://www.google.com/",
    "likes": "27",
    "userId": "64c786b6c7779aba85906df1"
}
